spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/blps?currentSchema=lab2
    username: postgres
    password:
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
#      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    defer-datasource-initialization: true
  data:
    redis:
      port: 6379
      host: localhost
  sql:
    init:
      mode: always
  quartz:
    job-store-type: jdbc
    jdbc:
      initialize-schema: always
server:
  port: 1234